site_name: Spaceflights

#nav:
#  - Home: index.md
#  - About: about.md

theme: material # readthedocs #material
markdown_extensions:
  - admonition
  - toc:
        baselevel: 3
  - attr_list

plugins:
  - search
  - mkdocstrings
#  - gen-files:
#      scripts:
#        - gen_pages.py




